[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Fusion description
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif _c.set == 'Joker' then'''
position = 'before'
match_indent = true
payload = '''
elseif _c.srl_fusion then
    localize{type = 'descriptions', set = 'Joker', key = _c.key, nodes = desc_nodes, vars = specific_vars or _c.vars, specific_vars = {is_info_queue = true}, AUT = full_UI_table}
'''

# Prevent "remove_from_deck" effect from fusion
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.added_to_deck = false'
position = 'after'
match_indent = true
payload = '''
if self.srl_ignore_remove_effects then return end
'''