[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Buff update
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'if G.STAGE == G.STAGES.RUN then'
position = 'after'
match_indent = true
payload = '''
    SRL_FUNC.apply_all_buffs()
'''