[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Class Orb, fusion, effect and minion tooltip and badges on card
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "for _, v in ipairs(info_queue) do"
position = "before"
payload = '''
if card and card.ability then
    if card.ability.srl_fusion then
        local _vars = {}
        if card.ability.srl_fusion.config.center.loc_vars then
            _vars = (card.ability.srl_fusion.config.center:loc_vars(info_queue, card.ability.srl_fusion))
            _vars = (_vars and _vars.vars) or {}
        end
        if is_info_queue then
            info_queue[#info_queue+1] = {srl_fusion = true, set = 'Joker', key = card.ability.srl_fusion.key, vars = _vars or {}}
        end
    end
    if card.ability.srl_class_orb and card.ability.srl_class_orb == "Ultimate" then
        info_queue[#info_queue+1] = {key = "srl_ultimate_class", set = "Other"}
    end

    if card.ability.srl_minion then
        local min_iq = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_minion.key]) or SRL_FUNC.min_iq(card.ability.srl_minion.name)
        if min_iq then
            info_queue[#info_queue+1] = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_minion.key]) or SRL_FUNC.min_iq(card.ability.srl_minion.name)
            if info_queue[#info_queue].config then
                info_queue[#info_queue].config.extra.rounds = card.ability.srl_minion_rounds or 1
            end
            G.BADGE_COL = G.BADGE_COL or {}
            G.BADGE_COL[card.ability.srl_minion.key] = G.C.FILTER
            badges[#badges + 1] = card.ability.srl_minion.key
        end
    end

    if card.ability.srl_effect_buff then
        local eff_iq = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_effect_buff.key]) or SRL_FUNC.eff_iq(card.ability.srl_effect_buff.name)
        if eff_iq then
            info_queue[#info_queue+1] = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_effect_buff.key]) or SRL_FUNC.eff_iq(card.ability.srl_effect_buff.name)
            if info_queue[#info_queue].config then
                info_queue[#info_queue].config.extra.rounds = card.ability.srl_effect_buff_rounds or 1
            end
            G.BADGE_COL = G.BADGE_COL or {}
            G.BADGE_COL[card.ability.srl_effect_buff.key] = G.C.GREEN
            badges[#badges + 1] = card.ability.srl_effect_buff.key
        end
    end

    if card.ability.srl_effect_debuff then
        local eff_iq = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_effect_debuff.key]) or SRL_FUNC.eff_iq(card.ability.srl_effect_debuff.name)
        if eff_iq then
            info_queue[#info_queue+1] = (card.ability.set and card.ability.set ~= "Default" and G.P_CENTERS[card.ability.srl_effect_debuff.key]) or SRL_FUNC.eff_iq(card.ability.srl_effect_debuff.name)
            if info_queue[#info_queue].config then
                info_queue[#info_queue].config.extra.rounds = card.ability.srl_effect_debuff_rounds or 1
            end
            G.BADGE_COL = G.BADGE_COL or {}
            G.BADGE_COL[card.ability.srl_effect_debuff.key] = G.C.RED
            badges[#badges + 1] = card.ability.srl_effect_debuff.key
        end
    end
end
'''
match_indent = true

# Sprite in description
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "elseif part.control.E then"
position = "before"
payload = '''
elseif part.control.srl_S then
    local sprite_size = 0.32*(part.control.s and tonumber(part.control.s) or 1)*desc_scale
    local center = G.P_CENTERS["eff_srl_" .. part.control.srl_S] or G.P_CENTERS["min_srl_" .. part.control.srl_S]
    if center then
        final_line[#final_line + 1] = {
            n = G.UIT.O,
            config = {
                object = Sprite(0, 0, sprite_size, sprite_size, G.ASSET_ATLAS[center.atlas .. "_mini"], {x = center.pos.x, y = center.pos.y})
            }
        }
    end
'''
match_indent = true

# Sprite in description box
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "elseif part.control.X or part.control.B then"
position = "before"
payload = '''
elseif part.control.srl_S then
    local sprite_mod = 0.32*(part.control.s and tonumber(part.control.s) or 1) * desc_scale
    local center = G.P_CENTERS["eff_srl_" .. part.control.srl_S] or G.P_CENTERS["min_srl_" .. part.control.srl_S]
    if center then
        final_line[#final_line + 1] = {
            n = G.UIT.O,
            config = {
                object = Sprite(0, 0, sprite_mod, sprite_mod, G.ASSET_ATLAS[center.atlas .. "_mini"], center.pos)
            }
        }
    end
'''
match_indent = true